In [1]:
import os
import pandas as pd
import sys
import veroviz as vrv
import numpy as np
from utils import getResults, getDirectory

In [2]:
experiment_id = "BNMC"
directory = getDirectory(experiment_id)
all_routes = getResults(directory)
all_routes.head(2)

,trip_id,bus_start_time,bus_end_time,bus_riding_time,walk_to_start_time,walk_to_destination_time,walk_to_start,walk_to_destination,total_walk_time,destination_id,...,end_stop_id,total_walk,total_time,start_time,end_time,bus_used,total_time_score,walking_score,time,preference
0,4560790.0,20069.0,20334.0,265.0,176.764432,201.247383,247.470205,281.746336,378.011816,1,...,30940.0,529.216542,643.011816,19892.23557,20535.24738,1,0.440271,0.75313,18000,min_time
1,4560790.0,20069.0,20334.0,265.0,176.764432,201.247383,247.470205,281.746336,378.011816,1,...,30940.0,529.216542,643.011816,19892.23557,20535.24738,1,0.440271,0.75313,18900,min_time